application: the-tomathon
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest


handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: images


- url: /.*
  script: main.app
